
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musinsa-api
    ports:
      - "5165:5165"
    networks:
      - musinsa_network
    volumes:
      - ./:/home/node/app/:rw

networks:
  musinsa_network: 
    name: musinsa_network
    external: true

